version: '2'
 
networks:
 fabric-ca:
 
services:
 rca-org0:
   container_name: rca-org0
   image: hyperledger/fabric-ca:latest
   command: sh -c 'fabric-ca-server start -b rca-org0-admin:rca-org0-adminpw --port 7053'
   environment:
     - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_CSR_CN=rca-org0
     - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
     - FABRIC_CA_SERVER_DEBUG=true
   volumes:
     - ../organizations/fabric-ca/ordererOrg:/tmp/hyperledger/fabric-ca
   networks:
     - fabric-ca
   ports:
     - 7053:7053
  
 rca-org1:
   container_name: rca-org1
   image: hyperledger/fabric-ca:latest
   command: sh -c 'fabric-ca-server start -b rca-org1-admin:rca-org1-adminpw'
   environment:
     - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_CSR_CN=rca-org1
     - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
     - FABRIC_CA_SERVER_DEBUG=true
   volumes:
     - ../organizations/fabric-ca/org1:/tmp/hyperledger/fabric-ca
   networks:
     - fabric-ca
   ports:
     - 7054:7054