# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
 
version: '3.8'
 
networks:
 capia:
   name: capia_network
 
services:
 
 ca_org1:
   image: hyperledger/fabric-ca:latest
   labels:
     service: hyperledger-fabric
   environment:
     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=tls-ca
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_PORT=7054
     - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
   ports:
     - "7054:7054"
     - "17054:17054"
   command: sh -c 'fabric-ca-server start -b admin:adminpw'
   volumes:
     - ../fabric-ca-server-tls/organizations/fabric-ca/tls:/etc/hyperledger/fabric-ca-server
   container_name: tls-ca
   networks:
     - capia
